# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        check-latest: true
    - name: maven-settings
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: '[{ "id": "central", "url": "https://repo1.maven.org/maven2" },{ "id": "github", "url": "https://maven.pkg.github.com/PAiC-team/*", "snapshots": {"enabled":true}}]'
        servers: |
          [{
              "id": "github",
              "username": "PAiC-team",
              "password": "${{ secrets.ACTION_BUILD_TOKEN }}"
          }]        
    - name: prebuild installations
      run: |
        chmod +x "${GITHUB_WORKSPACE}/.github/workflows/downloadartifact.sh"
        "${GITHUB_WORKSPACE}/.github/workflows/downloadartifact.sh"
    - name: Build with Maven
      run: mvn -B clean verify -Dmaven.test.skip=true --file pom.xml
